const projects = [{ "title": "YouVote - create and share polls", 
                    "tagline": "YouVote is a web application where users can create custom polls, save and share them with friends to get results.",
                    "features": [ "Create your own polls and share them with your friends.",
                                      "Poll results are displayed with an easy to read pie chart.",
                                      "Users may add new answers to existing polls from other users.",
                                      "Authentication is being handled via Facebook, therefor you can just use your Facebook account to log in."],
                    "thumbnail": "youvote-preview.jpg",
                    "images": [ "youvote-explore.png",
                                "youvote-main.png",
                                "youvote-new.png",
                                "youvote-poll.png",
                                "youvote-my.png" ],
                    "link": "https://raphaelmayer.github.io/youvote",
                    "repo": "https://github.com/raphaelmayer/Voting-App",
                    "tech": ["full stack", "react.js", "node.js", "mongoDB"]},
//
                  { "title": "Crawl-Unsplash-CLI", 
                    "tagline": "Crawl images on unsplash by topic and download them directly. - I worked on a project where I needed a lot of royalty-free images. Other crawlers were outdated and could not handle the infinite scroll of the new unsplash.com website, so I wrote this little command line tool to aid me.",
                    "features": [ "Discover and download images based on queries from the command line.",
                                  "Download hundreds of royalty free images with one command.",
                                  "Crawl-Unsplash-CLI offers the option to include a JSON file containing image information."],
                    "thumbnail": "crawl-unsplash-cl_bg.jpg",
                    "images": [ "crawl-unsplash-cl_bg.jpg" ],
                    "link": "",
                    "repo": "https://github.com/raphaelmayer/crawl-unsplash-cl",
                    "tech": ["misc", "node.js"]},
//
                  { "title": "Get Me a Goddamn Movie!", 
                    "tagline": "My girlfriend and I spent way too much time scrolling through Netflix to find something to watch. You just can't judge a movie by its cover! Consult ratings and movie trailers with ease to make an educated desicion.",
                    "features": [ "Discover by actor or movie. Additional filter and sort functionality.",
                                  "Results are paginated to ensure a crisp performance throughout.",
                                  "The app is linked with Youtube so you can watch trailers without searching first.",
                                  "Be up to date on new movie releases and popular movies within the community."],
                    "thumbnail": "gmagm_bg2.png",
                    "images": [ "GMAGM.jpg",
                                "GMAGM1.jpg",
                                "GMAGM3.jpg", ],
                    "link": "https://raphaelmayer.github.io/Get-Me-a-Goddamn-Movie",
                    "repo": "https://github.com/raphaelmayer/Get-Me-a-Goddamn-Movie",
                    "tech": ["front end", "react.js"]},  
//
                  { "title": "For Reddit, to Go", 
                    "tagline": "Listen to Reddit while getting stuff done - through the power of Text to Speech. - Currently in BETA. You may encounter unintended behaviour. Everything is subject to change.",
                    "features": [ "Comming soon" ],
                    "thumbnail": "rtg_bg.png",
                    "images": [ "rtg_bg.png" ],
                    "link": "https://raphaelmayer.github.io/ForRedditToGo",
                    "repo": "https://github.com/raphaelmayer/ForRedditToGo",
                    "tech": ["front end", "react.js", "javascript"]}, 
//
                  { "title": "Weather App", 
                    "tagline": "Lightweight, mobile-first web app to check your local weather or any location by name or ZIP-code in real time.",
                    "features": [ "Shows you the current weather aswell as a lot of other details like airpressure, windspeed, etc.",
                                      "Enter a city name and find out the current weather and forecast. Simple and easy.",
                                      "Gives you a 5-day weather forecast with temperature and weather details.",
                                      "Easy unit change with the press of a button."],
                    "thumbnail": "weatherApp_bg.png",
                    "images": [ "weatherApp.png" ],
                    "link": "https://raphaelmayer.github.io/weather-app",
                    "repo": "https://github.com/raphaelmayer/weather-app",
                    "tech": ["front end", "jQuery", "javascript"]}, 
//
                  { "title": "Simon Game", 
                    "tagline": "Simon Says is a classic game where the player has to reproduce a given sequence of button presses. With animation and sound.",
                    "features": [ "No library or framework was used. This project was built with vanilla JavaScript.",
                                      "Button presses give visual and audible feedback aswell as failing to reproduce the given sequence.",
                                      "Choose between Normal Mode (if you fail, you may try again) and Strict Mode (if you fail you lose the game and start from 1)"],
                    "thumbnail": "simon_bg.png",
                    "images": [ "simon-game.jpg" ],
                    "link": "https://raphaelmayer.github.io/simon-game",
                    "repo": "https://github.com/raphaelmayer/simon-game",
                    "tech": ["front end", "javascript"]},
//
                  { "title": "Choropleth Visualization", 
                    "tagline": "A map showing percentages of adults of age 25 and older with a bachelor's degree or higher (2010-2014)",
                    "features": [ "Interactive. Hover over counties to see the percentage and the name."],
                    "thumbnail": "choro_bg.png",
                    "images": [ "choro_bg.png" ],
                    "link": "https://raphaelmayer.github.io/choropleth_map",
                    "repo": "https://github.com/raphaelmayer/choropleth_map",
                    "tech": ["misc", "d3.js", "javascript"]}, 
//
                  { "title": "simple hotel landing page", 
                    "tagline": "My client wanted simple, easy to navigate landing page for his hotel to add to his online presence.",
                    "features": [ "Simple design and clear structure",
                                      "Integrated Google Maps API",
                                      "Contact Form" ],
                    "thumbnail": "hotel_bg.png",
                    "images": [ "hotel2.jpg" ],
                    "link": "",
                    "repo": "",
                    "tech": ["front end", "javascript", "Google Maps API"]},
//
                  { "title": "FoodShare", 
                    "tagline": "A Platform as a Service that aims to reduce the amount of food that gets thrown away.",
                    "features": [ "Comming soon" ],
                    "thumbnail": "placeholder.jpg",
                    "images": [ "placeholder.jpg" ],
                    "link": "",
                    "repo": "https://github.com/raphaelmayer/food-share",
                    "tech": ["full stack", "react.js", "node.js", "redux", "mongoDB"]}, 
//
                  { "title": "QuoteFactory", 
                    "tagline": "Coming soon - Realtime quote image generator with loads of options including font styles, filters and animations.",
                    "features": [ "Comming soon" ],
                    "thumbnail": "placeholder.jpg",
                    "images": [ "placeholder.jpg" ],
                    "link": "",
                    "repo": "",
                    "tech": ["full stack", "react.js", "node.js"]}, 
];
//
export default projects;